# Generated by Django 5.2.2 on 2025-06-10 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province_name', models.CharField(max_length=50)),
                ('province_code', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
