# Generated by Django 5.2.2 on 2025-06-10 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstap', '0002_province'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='province',
            name='province_code',
        ),
    ]
